-- Captura el esquema tal como quedo generado por Hibernate ddl-auto=update
-- hasta esta version. A partir de aca, cualquier cambio de esquema se hace
-- con un nuevo script Vn__descripcion.sql, nunca editando este archivo.
--
-- En una base ya existente (dev local) Flyway no ejecuta este script: lo usa
-- solo para marcar el baseline (ver spring.flyway.baseline-version en
-- application.properties). En una base nueva (CI, Docker, deploy limpio) si
-- se ejecuta y crea el esquema completo desde cero.

CREATE TABLE medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    especialidad VARCHAR(255),
    matricula VARCHAR(255),
    direccion VARCHAR(255),
    telefono VARCHAR(255),
    email VARCHAR(255),
    activo BOOLEAN,
    CONSTRAINT uk_medicos_email UNIQUE (email)
);

CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    dni VARCHAR(255),
    telefono VARCHAR(255),
    direccion VARCHAR(255),
    obra_social VARCHAR(255),
    numero_afiliado VARCHAR(255),
    plan VARCHAR(255),
    email VARCHAR(255),
    activo BOOLEAN,
    CONSTRAINT uk_pacientes_email UNIQUE (email)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    email VARCHAR(255),
    contrasena VARCHAR(255),
    role VARCHAR(255) CHECK (role IN ('ADMINISTRADOR', 'MEDICO', 'PACIENTE')),
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMP(6) WITHOUT TIME ZONE,
    especialidad VARCHAR(255),
    medico_id BIGINT,
    paciente_id BIGINT,
    estado VARCHAR(255) CHECK (estado IN ('PENDIENTE', 'CONFIRMADO', 'CANCELADO')),
    preparacion VARCHAR(255),
    CONSTRAINT uk_turnos_medico_fecha UNIQUE (medico_id, fecha_hora)
);

CREATE TABLE registros_clinicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP(6) WITHOUT TIME ZONE,
    medico_id BIGINT,
    paciente_id BIGINT,
    diagnostico VARCHAR(255),
    tratamiento VARCHAR(255),
    observaciones VARCHAR(255)
);
