spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medconnect}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
